version: '3.8'

services:
    mysql:
        image: mysql
        container_name: app_mysql
        working_dir: /home
        command: --default-authentication-plugin=mysql_native_password
        restart: on-failure
        environment:
            MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
            MYSQL_DATABASE: ${DB_NAME}
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        volumes:
            - ./db-data/mysql:/var/lib/mysql:rw
            - ./init/mysql:/docker-entrypoint-initdb.d
            - ./init/bkdata:/home/:rw
        ports:
            - "9906:3306"
    php:
        build:
            context: .
            target: app_php
        image: sf-docker/php:dev
        container_name: app_php
        working_dir: /var/www
        restart: on-failure
        environment:
            APP_ENV: dev
            APP_DEBUG: 1
            PHP_DATE_TIMEZONE: ${PHP_DATE_TIMEZONE:-UTC}
            XDEBUG_CONFIG: remote_host=docker.for.mac.localhost
            PHP_IDE_CONFIG: serverName=localhost
        depends_on:
            - mysql
        links:
            - "mysql:dbhost"
        volumes:
            -   ./src/${PROJECT_NAME}:/var/www/app:rw,cached
            -   ./src/${PROJECT_NAME2}:/var/www/app2:rw,cached

    nginx:
        build:
            context: .
            target: app_nginx
        image: sf-docker/nginx:dev
        container_name: app_web
        working_dir: /var/www
        restart: on-failure
        environment:
            - NGINX_HOST=localhost
            - NGINX_PORT=80
        depends_on:
            - php
        volumes:
            - ./src/${PROJECT_NAME}:/var/www/app
            - ./src/${PROJECT_NAME}:/var/www/app2
            - ./docker/nginx/conf.d:/etc/nginx/conf.d
        ports:
            - "1080:80"
            - "1081:81"
